//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.26 at 12:31:24 AM IST 
//


package Examples;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the Examples package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: Examples
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Restaurants }
     * 
     */
    public Restaurants createRestaurants() {
        return new Restaurants();
    }

    /**
     * Create an instance of {@link Restaurants.Restaurant }
     * 
     */
    public Restaurants.Restaurant createRestaurantsRestaurant() {
        return new Restaurants.Restaurant();
    }

    /**
     * Create an instance of {@link Restaurants.Restaurant.Food }
     * 
     */
    public Restaurants.Restaurant.Food createRestaurantsRestaurantFood() {
        return new Restaurants.Restaurant.Food();
    }

}
